# Generated by Django 3.1.1 on 2020-11-18 19:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import users.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='test.jpg', upload_to='user_pics')),
                ('height', models.DecimalField(decimal_places=2, max_digits=5, validators=[users.models.validate_input])),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5, validators=[users.models.validate_input])),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=10)),
                ('age', models.IntegerField(validators=[users.models.validate_input])),
                ('lifestyle', models.CharField(choices=[('Sedentary or light activity', 'Sedentary or light activity'), ('Active or moderately active', 'Active or moderately active'), ('Vigorously active', 'Vigorously active')], default='Sedentary or light activity', max_length=50)),
                ('calorie_goal', models.CharField(max_length=20)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.plancategory')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
