# Generated by Django 3.1.1 on 2020-11-20 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20201119_0141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='profile',
            name='lifestyle',
            field=models.CharField(max_length=50),
        ),
    ]
