# Generated by Django 3.1.1 on 2020-11-24 13:59

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20201124_1920'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
                ('calories', models.CharField(max_length=20)),
                ('fats', models.CharField(max_length=20)),
                ('proteins', models.CharField(max_length=20)),
                ('carbs', models.CharField(max_length=20)),
                ('date_added', models.DateField(default=django.utils.timezone.now)),
                ('meal_cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.mealcategory')),
            ],
        ),
    ]
