# Generated by Django 3.1.1 on 2020-11-28 12:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0005_auto_20201128_1424'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfooditems',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userfooditems',
            name='calories',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='userfooditems',
            name='carbs',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='userfooditems',
            name='fats',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='userfooditems',
            name='meal_cat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.mealcategory'),
        ),
        migrations.AlterField(
            model_name='userfooditems',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userfooditems',
            name='proteins',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='userfooditems',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
