# Generated by Django 3.1.1 on 2020-12-16 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_auto_20201216_2056'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pastrecords',
            options={'verbose_name': 'Past Record'},
        ),
    ]
